Repository rktejesh/Fluttadex, pull requests merged in 2022-03, with the labels that each got.

#17 Implement Appbar Widget #3
  lib/routes/appBar.dart
  lib/widget_list.dart
Labels: accepted-3

#19 Implement a splash screen #18
  assets/Images/flutterIcon.png
  lib/home.dart
  lib/main.dart
  lib/splash_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: accepted-5

#21 Implemented icon widget
  lib/routes/icon.dart
  lib/widget_list.dart
Labels: accepted-3

#22 Implement Floating Action Button Widget #12
  lib/routes/floatingActionButton.dart
  lib/widget_list.dart
  pubspec.lock
  pubspec.yaml
Labels: accepted-3

#27 converted to Stateful widget
  lib/routes/elevatedButton.dart
Labels: accepted-2

#40 Implement Card Widget #5
  lib/routes/cards.dart
  lib/widget_list.dart
Labels: accepted-5

#41 added padding
  lib/routes/image.dart
Labels: accepted-3

#42 Implemented checkbox
  lib/routes/checkbox.dart
  lib/widget_list.dart
Labels: accepted-3

#43 added form implementation
  assets/Images/register_bg.png
  lib/routes/form.dart
  lib/widget_list.dart
Labels: accepted-3
